# Generated by Django 6.0.5 on 2026-05-10 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('buyer', 'buyer'), ('seller', 'seller')], default='buyer', max_length=20),
        ),
    ]
