# Generated by Django 6.0.5 on 2026-05-10 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art_app', '0002_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='rank',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='total_volume',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
