# Generated by Django 6.0.5 on 2026-05-10 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art_app', '0003_user_is_verified_user_rank_user_total_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='facebook_link',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='instagram_link',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='linkedin_link',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='twitter_link',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
